# =============================================================================
# comparison_study_v2.jl  --  M-route vs N-route, scored against the ORACLE
#
# CHANGE FROM v1: ground truth is no longer m_route(chi).
#
# v1 set c_exact = dynamic_mpf_coefficients(M, L) at the ceiling -- the M-route
# solving its own Lagrange system. Job 6974035 showed that is off from the true
# value by 6.9e-6, and the STALE CSVs generated by an older revision were off by
# 9.5e-5. Ground truth is now validate_N_against_direct: evolve rho_kj and
# rho_ref as MPS, form delta_j, take inner products.
#
# The oracle is EXACT and CHEAP, for a reason worth restating:
#     MPS ceiling = 4^min(l,n-l)   =  16 at n=4,  64 at n=6
#     MPO ceiling = 16^min(l,n-l)  = 256 at n=4, 4096 at n=6
# theoretical_max_bond_dim is the MPO ceiling. The oracle manipulates an MPS, so
# it saturates 16x lower at n=4 and 64x lower at n=6. Job 6974035 Part 0 measured
# dc vs prev = 0.00e+00 (exactly) from maxdim=16 up. This script re-verifies that
# every run rather than assuming it.
#
# ALSO NEW:
#   - maxdim_G and N12 are recorded. Both were invisible in v1's output, and
#     maxdim_G silently moved the answer by an order of magnitude.
#   - c1_free and signal (check 0's free-formula baseline) so every run scores
#     itself against "was this worth computing at all".
#   - dc_vs_lagrange kept alongside dc_max so the old and new references can be
#     compared rather than silently swapped.
#
# COLUMN ORDER NOTE: field 5 of cmp_coefficients.csv is still dc_max, because
# spectra_study.jl parses it positionally (line 101). Do not reorder.
#
# Retained from v1: keep the SIGN of every error. The M-route returns NEGATIVE
# squared norms and that is the headline. Never plot |E| without a sign flag.
#
# Environment: N_QUBITS, GAMMA, TVAL, K0, K_REF, ORDER, TAG, GSCAN
#   GSCAN=1 additionally sweeps maxdim_G at each maxdim -> cmp_gscan.csv
#   MAXCHI  caps the MPO grid (default min(ceiling, 256))
#   CUTOFF        SVD cutoff for the MPO routes (default 1e-14)
#   CUTOFF_ORACLE SVD cutoff for the oracle only (default = CUTOFF)
#   GRID    explicit comma-separated grid, e.g. GRID=64,128,256,384,512
# =============================================================================

import Distributions, Random
using LinearAlgebra, Printf
include("trotter_error_gram.jl")
include("open_optimization_problem.jl")   # expect constant-redefinition warnings;
                                          # harmless, both chain to F_diagnostics
BLAS.set_num_threads(parse(Int, get(ENV, "SLURM_CPUS_PER_TASK", "1")))

getenv(k, d) = get(ENV, k, string(d))
n     = parse(Int,     getenv("N_QUBITS", 4))
gamma = parse(Float64, getenv("GAMMA",    0.05))
t     = parse(Float64, getenv("TVAL",     3.0))
k0    = parse(Int,     getenv("K0",       48))
k_ref = parse(Int,     getenv("K_REF",    48))
order = parse(Int,     getenv("ORDER",    2))
tag   = getenv("TAG", "")
gscan = getenv("GSCAN", "0") == "1"
ks    = [3, 8]
ct    = parse(Float64, getenv("CUTOFF", 1e-14))          # for the MPO routes
# The ORACLE gets its own cutoff. At n=6 job 6995914 showed the oracle drifting
# 4.7e-4 between maxdim 64 and 128, which is impossible as a bond-dimension
# effect (the MPS ceiling is 4^3 = 64, so 128 cannot add states). The suspect is
# cutoff: delta_j = rho_kj - rho_ref is a small difference of two O(1) states, so
# a cutoff relative to the large intermediate is far too loose for the small
# result. The oracle is CHEAP, so it can afford a tighter cutoff than the routes.
ct_orc = parse(Float64, getenv("CUTOFF_ORACLE", ct))

@assert k_ref == k0 "k_ref must equal k0, else the routes target different references"

chi     = theoretical_max_bond_dim(n)          # MPO ceiling
chi_mps = 4^min(n ÷ 2, n - n ÷ 2)              # MPS ceiling (the oracle's)

# MAXCHI caps everything the MPO routes do. At n=4 the ceiling is 256 and is
# reachable; at n=6 it is 4096 and is NOT. v2 hard-coded m_route(chi) for the v1
# reference, which at n=6 would launch a maxdim=4096 run -- days, and out of
# memory. Cap it, and say so in the log.
default_grid = [16, 32, 48, 64, 96, 128, 192, 256]
maxchi  = parse(Int, getenv("MAXCHI", min(chi, maximum(default_grid))))
grid    = haskey(ENV, "GRID") ?
          sort(parse.(Int, split(ENV["GRID"], ","))) :
          filter(<=(maxchi), default_grid)
grid    = filter(<=(min(chi, maxchi)), grid)
chi_ref = maximum(grid)                        # best MPO point we can afford
sfx     = isempty(tag) ? "" : "_" * tag

@printf("n=%d gamma=%.3f t=%.1f ks=%s k0=%d k_ref=%d order=%d\n",
        n, gamma, t, string(ks), k0, k_ref, order)
@printf("MPO ceiling = %d    MPS ceiling (oracle) = %d\n", chi, chi_mps)
@printf("grid = %s   (capped at %d)\n", string(grid), chi_ref)
@printf("cutoff: routes = %.1e   oracle = %.1e\n", ct, ct_orc)
if chi_ref < chi
    println("""
  *** THE MPO CEILING IS NOT REACHED. Every point below is TRUNCATED. ***
  At n=4 the maxdim=256 run was exact and both routes agreed to ~7e-6; there is
  no such point here. The oracle is the ONLY exact object in this run -- which is
  the whole reason it was made the ground truth. Note the oracle saturates at
  maxdim=$chi_mps, i.e. $(round(Int, chi/chi_mps))x below what the MPO routes would need.
""")
end
println()
flush(stdout)

Random.seed!(1234)
J      = rand(Distributions.Uniform(1/4, 3/4), n - 1)
gammas = fill(gamma, n)
lsites = liouville_siteinds(n)
rho0   = vectorized_initial_state_mps(lsites, collect(0:2:(n-1)) .|> string)

build_N(M, L, P) = [M[i,j] - L[i] - L[j] + P for i in 1:length(L), j in 1:length(L)]

# ---- check 0's free formula -------------------------------------------------
# Richardson corrected for the finite reference E = S(t/k0)^k0, which carries its
# own k0^-p error. Depends ONLY on (ks, order, k0): the SAME value for every n,
# gamma and t. Costs nothing, and reproduces ~90% of c. See
# findings_check0_free_baseline.md.
function richardson_coeffs(ks, p, k0)
    u = [float(k)^(-p) - float(k0)^(-p) for k in ks]
    return [1.0 1.0; u[1] u[2]] \ [1.0, 0.0]
end
c_free = richardson_coeffs(ks, order, k0)

function m_route(md)
    M, _ = open_gram_matrix(n, J, gammas, t, ks, lsites, rho0;
                            cutoff=ct, maxdim=md, order=order, dissipation=true)
    L, _ = open_L_vector(n, J, gammas, t, ks, k_ref, lsites, rho0;
                         cutoff=ct, maxdim=md, order=order, order_ref=order, dissipation=true)
    P = reference_purity(n, J, gammas, t, k_ref, lsites, rho0;
                         cutoff=ct, maxdim=md, order=order, dissipation=true)
    c, _ = dynamic_mpf_coefficients(M, L)
    N = build_N(M, L, P)
    (c=c, E_mpf=open_dynamic_mpf_error(M, L, c, P), N=N,
     lam=minimum(eigen(Symmetric(0.5 * (N + N'))).values))
end

# ---- ground truth: the oracle, self-verified --------------------------------
println("="^76); println("GROUND TRUTH: direct state-overlap oracle"); println("="^76)

function oracle_at(md)
    validate_N_against_direct(n, J, gammas, t, ks, k_ref, lsites, rho0;
                              cutoff=ct_orc, maxdim=md, order=order,
                              order_ref=order, dissipation=true)
end

# The oracle MUST run AT the MPS ceiling, never above it. Job 7033426 measured
# c1 = -0.13342 / -0.13573 / -0.13620 / -0.13566 at maxdim = 32 / 64 / 128 / 256,
# reproducibly at every cutoff from 1e-12 to 0. maxdim=64 and 256 agree to 7.1e-5
# while 128 is off from BOTH by ~5e-4 -- that is not convergence drift, it is the
# above-ceiling pathology already documented at trotter_error_gram.jl:72
# ("actively harmful ... enormous intermediate tensors"). v3 previously took
# oracle_at(2*chi_mps) as ground truth, i.e. deliberately the polluted one.
# maxdim = chi_mps is exact by representability: an MPS on n Liouville sites of
# local dimension 4 has Schmidt rank at most 4^min(l,n-l) at every cut.
N_lo, N_hi = oracle_at(chi_mps ÷ 2), oracle_at(chi_mps)
c_lo = trotter_error_coefficients(N_lo).coeffs
c_hi = trotter_error_coefficients(N_hi).coeffs
drift = maximum(abs.(c_hi .- c_lo))
@printf("  maxdim=%d (below ceiling)  c1=%+.10f\n  maxdim=%d (AT ceiling)     c1=%+.10f\n  gap = %.3e\n",
        chi_mps ÷ 2, c_lo[1], chi_mps, c_hi[1], drift)
println("""  The ceiling value is exact by representability. The gap above is how
  much the half-ceiling run is truncating -- it is NOT a convergence error, and
  it does NOT need to be small. Do NOT 'check' this by raising maxdim above
  $chi_mps: that is the above-ceiling pathology (section 4 note) and it silently
  shifts c1 by ~5e-4 at n=6.""")

N_oracle = N_hi
c_exact  = c_hi
Ek_exact = [N_oracle[j,j] for j in 1:length(ks)]
E_mpf_ex = trotter_error_coefficients(N_oracle).E_mpf
lam_ex   = minimum(eigen(Symmetric(0.5 * (N_oracle + N_oracle'))).values)
signal   = maximum(abs.(c_exact .- c_free))

@printf("\n  c_exact = [%+.8f, %+.8f]\n", c_exact[1], c_exact[2])
@printf("  N11 = %.8e  N12 = %.8e  N22 = %.8e\n", N_oracle[1,1], N_oracle[1,2], N_oracle[2,2])
@printf("  E_mpf = %.6e   lambda_min = %.4e\n", E_mpf_ex, lam_ex)

# the v1 reference, kept for comparison
ex_lag = m_route(chi_ref)
@printf("\n  v1 reference (Lagrange in M,L at maxdim=%d): c1 = %+.8f\n", chi_ref, ex_lag.c[1])
@printf("  |v1 - oracle| = %.3e   <- how wrong the old ground truth was\n",
        maximum(abs.(ex_lag.c .- c_exact)))

@printf("\n  FREE FORMULA  c1_free = %+.8f   signal = %.4e\n", c_free[1], signal)
println("  Anything with dc_max above the signal lost to a hand-evaluable formula.")
println("\nCAVEAT: k_ref=$k_ref is UNTRUNCATED but not physically converged. The")
println("two-term model predicts E_k8 rising +5.85% as k0 -> inf, with")
println("c1 -> -0.148883 at these parameters. Still untested; run K0=192.\n")
flush(stdout)

# ---- sweep ------------------------------------------------------------------
rc = ["maxdim,route,c1,c2,dc_max,dc_vs_lagrange,maxdim_G,c1_free,signal"]
re = ["maxdim,maxdim_G,route,E_mpf,E_k3,E_k8,N12,lambda_min,resolved,time_s"]

println("maxdim | M: c1        dc        E_k8       | N: c1        dc        E_k8       | t_M   t_N")
println("-"^104)

function sweep!(rc, re, grid)
    for md in grid
        t0 = time(); m = m_route(md); tM = time() - t0
        t0 = time()
        r = test_dmpf_open_N(n, J, gammas, t, ks, k0, lsites, rho0;
                             cutoff=ct, maxdim=md, maxdim_G=md,
                             order=order, order_ref=order, dissipation=true,
                             exact_delta=true)
        tN = time() - t0

        dM  = maximum(abs.(m.c      .- c_exact))
        dN  = maximum(abs.(r.coeffs .- c_exact))
        dML = maximum(abs.(m.c      .- ex_lag.c))
        dNL = maximum(abs.(r.coeffs .- ex_lag.c))

        push!(rc, @sprintf("%d,M,%.8f,%.8f,%.8e,%.8e,%d,%.8f,%.8e",
                           md, m.c[1], m.c[2], dM, dML, md, c_free[1], signal))
        push!(rc, @sprintf("%d,N,%.8f,%.8f,%.8e,%.8e,%d,%.8f,%.8e",
                           md, r.coeffs[1], r.coeffs[2], dN, dNL, md, c_free[1], signal))
        push!(re, @sprintf("%d,%d,M,%.8e,%.8e,%.8e,%.8e,%.8e,%s,%.1f",
                           md, md, m.E_mpf, m.N[1,1], m.N[2,2], m.N[1,2],
                           m.lam, m.lam > 0 ? "yes" : "no", tM))
        push!(re, @sprintf("%d,%d,N,%.8e,%.8e,%.8e,%.8e,%.8e,%s,%.1f",
                           md, md, r.E_mpf, r.E_trot[1], r.E_trot[2], r.N[1,2],
                           minimum(r.eigvals), minimum(r.eigvals) > 0 ? "yes" : "no", tN))

        @printf("%6d | %+.5f %.2e %+.3e | %+.5f %.2e %+.3e | %5.0f %5.0f\n",
                md, m.c[1], dM, m.N[2,2], r.coeffs[1], dN, r.E_trot[2], tM, tN)
        # write after every maxdim so a timeout does not cost the whole sweep
        write("cmp_coefficients$sfx.csv", join(rc, "\n") * "\n")
        write("cmp_errors$sfx.csv",       join(re, "\n") * "\n")
        flush(stdout)
    end
end

sweep!(rc, re, grid)
println("\nwrote cmp_coefficients$sfx.csv, cmp_errors$sfx.csv")

# ---- optional joint maxdim x maxdim_G scan ----------------------------------
# Job 6974035 Part 2 found every maxdim_G down to 16 beat the free formula at
# fixed maxdim=256. If that holds along the diagonal too, G -- the expensive
# object -- can run far below the ceiling for free. GSCAN=1 tests it.
function gscan!(rows, grid)
    for md in grid, mg in filter(<=(md), [16, 32, 64, 128, 192, 256])
        t0 = time()
        r = test_dmpf_open_N(n, J, gammas, t, ks, k0, lsites, rho0;
                             cutoff=ct, maxdim=md, maxdim_G=mg,
                             order=order, order_ref=order, dissipation=true,
                             exact_delta=true)
        el = time() - t0
        d  = maximum(abs.(r.coeffs .- c_exact))
        push!(rows, @sprintf("%d,%d,%.8f,%.8e,%.8e,%.8e,%.8e,%.8e,%.1f",
                             md, mg, r.coeffs[1], d, signal,
                             r.N[1,1], r.N[1,2], r.N[2,2], el))
        @printf("  maxdim=%4d maxdim_G=%4d  c1=%+.6f  dc=%.3e  (%.2f x signal)  %5.0f s\n",
                md, mg, r.coeffs[1], d, d / signal, el)
        write("cmp_gscan$sfx.csv", join(rows, "\n") * "\n")
        flush(stdout)
    end
end

if gscan
    println("\n" * "="^76)
    println("JOINT SCAN: maxdim x maxdim_G  (GSCAN=1)")
    println("="^76)
    gr = ["maxdim,maxdim_G,c1,dc_max,signal,N11,N12,N22,time_s"]
    gscan!(gr, grid)
    println("\nwrote cmp_gscan$sfx.csv")
end

println("\nNOTE: spectra_study.jl reads dc_max positionally from field 5 of")
println("cmp_coefficients$sfx.csv, so re-running it now picks up the oracle-")
println("referenced errors with no edit. Run it after this to refresh")
println("cmp_spectra$sfx.csv and cmp_weight_vs_error$sfx.csv.")
